version: '3.8'

services:
  app:
    build: .
    container_name: recipeBook
    ports:
      - "8080:8080"
      - "9092:9092"
  # tests:
  #   build: ./test
  #   container_name: test
  #   depends_on:
  #     - app
